apiVersion: v2
name: vector
description: Vector日志收集器Helm Chart
type: application
version: 0.1.0
appVersion: "0.32.0"
keywords:
  - vector
  - logging
  - observability
  - datadog
home: https://vector.dev/
sources:
  - https://github.com/vectordotdev/vector
maintainers:
  - name: Vector Demo
    email: demo@example.com
